routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/logout', 'Auth\LoginController@logout');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::patch('admin/branch/status/{branch}', 'BranchesController@status');

Route::resource('admin/branch', 'BranchesController');

Route::patch('admin/users/status/{user}', 'UsersController@status');

Route::resource('admin/users', 'UsersController');

Route::resource('admin/banks', 'BanksController');

Route::resource('admin/roles', 'RolesController');

Route::resource('admin/brands', 'BrandsController');

Route::patch('admin/products/status/{products}', 'ProductsController@status');

Route::resource('admin/products', 'ProductsController');

//Route::group(['middleware'=>['admin', 'user']], function () {
//    Route::resource('transactions', 'DateWiseTransactionsController');
//});
Route::resource('transactions', 'DateWiseTransactionsController');

Route::resource('bankcharges', 'BankChargesController');

app/BankCharge.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BankCharge extends Model
{
    protected $table = 'bank_charges_summary';

    protected $dates = [
        'trans_date'
    ];

}

app/Http/Controllers/BankChargesController.php
<?php

namespace App\Http\Controllers;

use App\Bank;
use App\BankCharge;
use App\BankChargeDetail;
use App\Branch;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BankChargesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
//        $this->middleware('user');
        $this->middleware('admin');
    }

    public function index()
    {
        $charges = BankChargeDetail::where('created_by', Auth::user()->id)->get();
//        dd($charges->trans_id);
        return view('BankCharges.index', compact('charges'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $branch = Auth::user()->branches->first()->id;
        $branch_name = Auth::user()->branches->first()->name;
//        dd($branch_name);

        $branchBank = Branch::find($branch)->banks->pluck('id');

        $banks = Bank::whereIn('id', $branchBank)->get();

//        dd($banks);

        return view('BankCharges.create',compact('branch','banks','branch_name'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $trans_date = Carbon::parse($request->trans_date)->toDateString();
        $dd = str_replace('-', '', $trans_date);
        $year = substr($dd,0,4);
        $month = substr($dd,4,2);
        $day = substr($dd,6,2);
        $user_id = Auth::user()->id;
        $trans_sl = str_pad(BankChargeDetail::count()+1, 6, '0', STR_PAD_LEFT);
        $trans_id = substr($request->branch_name,0,3).'-'.$dd.'-'.(BankChargeDetail::count()+1);


        $total = 0;
        foreach ($request->bank as $key=>$value){
            $bank_id = $key;
            $amount = $value;
            $bank_name = Bank::find($bank_id)->short_name;
            //dd($user_id);

            $summary = new BankCharge;
            $summary->trans_id = $trans_id;
            $summary->trans_sl = $trans_sl;
            $summary->bank_id = $bank_id;
            $summary->bank_name = $bank_name;
            $summary->amount = $amount;
            $summary->save();
            $total = $total+$amount;
//            dd($total);

        }
        $detail = new BankChargeDetail;

        $detail->trans_id = $trans_id;
        $detail->trans_sl = $trans_sl;
        $detail->trans_date = $trans_date;
        $detail->year = $year;
        $detail->month = $month;
        $detail->day = $day;
        $detail->total = $total;
        $detail->branch_id = $request->branch;
        $detail->branch_name = $request->branch_name;
        $detail->created_by = $user_id;

        $detail->save();

        return redirect('/bankcharges')->with('success', 'Bank Charges Created Successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $bank_trans = BankChargeDetail::findOrFail($id);

        return view('BankCharges.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/BankCharges/create.blade.php
@extends('layouts.app')

@section('content')

    <div id="page-wrapper">
        <style>
            .modal-confirm {
                color: #636363;
                width: 400px;
            }
            .modal-confirm .modal-content {
                padding: 20px;
                border-radius: 5px;
                border: none;
                text-align: center;
                font-size: 14px;
            }
            .modal-confirm .modal-header {
                border-bottom: none;
                position: relative;
            }
            .modal-confirm h4 {
                text-align: center;
                font-size: 26px;
                margin: 30px 0 -10px;
            }
            .modal-confirm .close {
                position: absolute;
                top: -5px;
                right: -2px;
            }
            .modal-confirm .modal-body {
                color: #000000;
            }
            .modal-confirm .modal-footer {
                border: none;
                text-align: center;
                border-radius: 5px;
                font-size: 13px;
                padding: 10px 15px 25px;
            }
            .modal-confirm .modal-footer a {
                color: #999;
            }
            .modal-confirm .icon-box {
                width: 80px;
                height: 80px;
                margin: 0 auto;
                border-radius: 50%;
                z-index: 9;
                text-align: center;
                border: 3px solid #f15e5e;
            }
            .modal-confirm .icon-box i {
                color: #f15e5e;
                font-size: 46px;
                display: inline-block;
                margin-top: 13px;
            }
            #table .form-control{
                height: 25px;
            }
            .require:after{
                content:'*';
                color:red;
            }
            input[type=number]{
                text-align: right;
            }

        </style>
        <div class="row" style="padding-top: 50px">
            <div class="col-lg-8 col-lg-offset-2">
                @include('includes.messages')
                <h4><strong>Bank Charges</strong></h4>
                <div class="panel-heading col-lg-3">
                    {!! Form::open(['method'=>'POST', 'action'=>'BankChargesController@store']) !!}
                    {!! Form::label('', 'Date', ['class'=>'require']) !!}
                    {!! Form::text('trans_date', null, ['class'=>'form-control datepicker', 'id'=>'date','required', 'placeholder'=>'DD/MM/YYYY']) !!}
                </div>
                <div class="col-lg-9">
                    <div class="panel-heading pull-right">
                        {!! Form::label('', 'Branch') !!}
                        {!! Form::hidden('branch', $branch) !!}
                        {!! Form::hidden('branch_name', $branch_name) !!}
                        {!! Form::text('', $branch_name, ['class'=>'form-control', 'disabled']) !!}
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table width="100%" class="table table-striped table-bordered table-hover" id="table">
                            <thead>
                            <tr class="info">
                                <th>SL</th>
                                <th>Bank Name</th>
                                <th>Amount</th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($banks as $bank)
                            <tr class="info">
                                <th class="col-lg-1">{{$loop->iteration}}</th>
                                <td class="col-lg-2">{{$bank->short_name}}</td>
                                <td class="col-lg-2">{!! Form::number('bank['.$bank->id.'],[amount]', null, ['class'=>'form-control']) !!}</td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <!-- /.table-responsive -->
                        <div class="col-lg-12 text-center">
                            {{ Form::button('<i class="fa fa-check"></i> Save', ['type' => 'submit', 'class' => 'btn btn-primary'] ) }}
                            <a href="" class="btn btn-warning"><i class="fa fa-reply"></i> Cancel</a>
                        </div>
                    </div>

                {!! Form::close() !!}
                <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
    </div>
@endsection

resources/views/BankCharges/edit.blade.php
@extends('layouts.app')

@section('content')

    <div id="page-wrapper">
        <style>
            .modal-confirm {
                color: #636363;
                width: 400px;
            }
            .modal-confirm .modal-content {
                padding: 20px;
                border-radius: 5px;
                border: none;
                text-align: center;
                font-size: 14px;
            }
            .modal-confirm .modal-header {
                border-bottom: none;
                position: relative;
            }
            .modal-confirm h4 {
                text-align: center;
                font-size: 26px;
                margin: 30px 0 -10px;
            }
            .modal-confirm .close {
                position: absolute;
                top: -5px;
                right: -2px;
            }
            .modal-confirm .modal-body {
                color: #000000;
            }
            .modal-confirm .modal-footer {
                border: none;
                text-align: center;
                border-radius: 5px;
                font-size: 13px;
                padding: 10px 15px 25px;
            }
            .modal-confirm .modal-footer a {
                color: #999;
            }
            .modal-confirm .icon-box {
                width: 80px;
                height: 80px;
                margin: 0 auto;
                border-radius: 50%;
                z-index: 9;
                text-align: center;
                border: 3px solid #f15e5e;
            }
            .modal-confirm .icon-box i {
                color: #f15e5e;
                font-size: 46px;
                display: inline-block;
                margin-top: 13px;
            }
            #table .form-control{
                height: 25px;
            }
            .require:after{
                content:'*';
                color:red;
            }
            input[type=number]{
                text-align: right;
            }

        </style>
        <div class="row" style="padding-top: 50px">
            <div class="col-lg-8 col-lg-offset-2">
                @include('includes.messages')
                <h4><strong>Update Bank Charges</strong></h4>
                <div class="panel-heading col-lg-3">
                    {!! Form::model(['method'=>'POST', 'action'=>'BankChargesController@update']) !!}
                    {!! Form::label('', 'Date', ['class'=>'require']) !!}
                    {!! Form::text('trans_date', null, ['class'=>'form-control datepicker', 'id'=>'date','required', 'placeholder'=>'DD/MM/YYYY']) !!}
                </div>
                {{--<div class="col-lg-9">--}}
                    {{--<div class="panel-heading pull-right">--}}
                        {{--{!! Form::label('', 'Branch') !!}--}}
                        {{--{!! Form::hidden('branch', $branch) !!}--}}
                        {{--{!! Form::hidden('branch_name', $branch_name) !!}--}}
                        {{--{!! Form::text('', $branch_name, ['class'=>'form-control', 'disabled']) !!}--}}
                    {{--</div>--}}
                {{--</div>--}}
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table width="100%" class="table table-striped table-bordered table-hover" id="table">
                            <thead>
                            <tr class="info">
                                <th>SL</th>
                                <th>Bank Name</th>
                                <th>Amount</th>
                            </tr>
                            </thead>
                            <tbody>

                            {{--@foreach($banks as $bank)--}}
                                {{--<tr class="info">--}}
                                    {{--<th class="col-lg-1">{{$loop->iteration}}</th>--}}
                                    {{--<td class="col-lg-2">{{$bank->short_name}}</td>--}}
                                    {{--<td class="col-lg-2">{!! Form::number('bank['.$bank->id.'],[amount]', null, ['class'=>'form-control']) !!}</td>--}}
                                {{--</tr>--}}
                            {{--@endforeach--}}
                            {{--</tbody>--}}
                        </table>
                        <!-- /.table-responsive -->
                        <div class="col-lg-12 text-center">
                            {{ Form::button('<i class="fa fa-check"></i> Save', ['type' => 'submit', 'class' => 'btn btn-primary'] ) }}
                            <a href="" class="btn btn-warning"><i class="fa fa-reply"></i> Cancel</a>
                        </div>
                    </div>

                {!! Form::close() !!}
                <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
    </div>
@endsection

resources/views/BankCharges/index.blade.php
@extends('layouts.app')

@section('content')

    <div id="page-wrapper">
        <style>
            .modal-confirm {
                color: #636363;
                width: 400px;
            }
            .modal-confirm .modal-content {
                padding: 20px;
                border-radius: 5px;
                border: none;
                text-align: center;
                font-size: 14px;
            }
            .modal-confirm .modal-header {
                border-bottom: none;
                position: relative;
            }
            .modal-confirm h4 {
                text-align: center;
                font-size: 26px;
                margin: 30px 0 -10px;
            }
            .modal-confirm .close {
                position: absolute;
                top: -5px;
                right: -2px;
            }
            .modal-confirm .modal-body {
                color: #000000;
            }
            .modal-confirm .modal-footer {
                border: none;
                text-align: center;
                border-radius: 5px;
                font-size: 13px;
                padding: 10px 15px 25px;
            }
            .modal-confirm .modal-footer a {
                color: #999;
            }
            .modal-confirm .icon-box {
                width: 80px;
                height: 80px;
                margin: 0 auto;
                border-radius: 50%;
                z-index: 9;
                text-align: center;
                border: 3px solid #f15e5e;
            }
            .modal-confirm .icon-box i {
                color: #f15e5e;
                font-size: 46px;
                display: inline-block;
                margin-top: 13px;
            }

        </style>
        <div class="row" style="padding-top: 50px">
            <div class="col-lg-12">
                @include('includes.messages')
                <div class="col-lg-4">
                    <h4><strong>Bank Charges</strong></h4>
                </div>
                <div class="col-lg-8">
                    <div class="panel-heading pull-right">
                        <a href="{{route('bankcharges.index')}}" class="btn-default btn-sm"><i class="fa fa-server"></i> All Bank Charges</a>
                        <a href="{{route('bankcharges.create')}}" class="btn-primary btn-sm"><i class="fa fa-plus"></i> Add New</a>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table width="100%" class="table table-striped table-bordered table-hover" id="banktable">
                            <thead>
                            <tr class="danger">
                                <th>Date</th>
                                <th>Trans_ID</th>
                                <th>Trans_SL</th>
                                <th>Branch</th>
                                <th>Total</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($charges as $charge)
                                <tr class="success">
                                    <td>{{$charge->trans_date->format('d-M-Y')}}</td>
                                    <td>{{$charge->trans_id}}</td>
                                    <td>{{$charge->trans_sl}}</td>
                                    <td>{{$charge->branch_name}}</td>
                                    <td style="text-align: center">{{$charge->total}}</td>
                                    <td>
                                        {{--<a href="{{route('users.show', $user->id)}}" class="btn btn-primary btn-xs">View</a>--}}
                                        <a href="{{route('bankcharges.edit', $charge->id)}}" class="btn btn-info btn-xs">Edit</a>
                                        {{--<button href="#myModal" class="btn-xs btn-danger" data-toggle="modal">Delete</button>--}}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
    </div>

    <!-- Modal HTML -->
    {{--<div id="myModal" class="modal fade">--}}
        {{--<div class="modal-dialog modal-confirm">--}}
            {{--<div class="modal-content">--}}
                {{--<div class="modal-header">--}}
                    {{--<div class="icon-box">--}}
                        {{--<i class="fa fa-times-circle"></i>--}}
                    {{--</div>--}}
                    {{--<h4 class="modal-title">Are you sure?</h4>--}}
                    {{--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>--}}
                {{--</div>--}}
                {{--<div class="modal-body">--}}
                    {{--<p>Do you really want to delete these records? This process cannot be undone.</p>--}}
                {{--</div>--}}
                {{--<div class="modal-footer">--}}
                    {{--<button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>--}}
                    {{--<button style="border: none; background: none">--}}
                        {{--{!! Form::open(['method'=>'DELETE', 'action'=>['UsersController@destroy', $user->id]]) !!}--}}
                        {{--{!! Form::submit('Delete', ['class'=>'btn btn-danger']) !!}--}}
                        {{--{!! Form::close() !!}--}}
                    {{--</button>--}}
                {{--</div>--}}
            {{--</div>--}}
        {{--</div>--}}
    {{--</div>--}}

@endsection